<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Priority</name>
   <tag></tag>
   <elementGuidId>b600d61a-fcc1-46ce-b96c-aec0c9f2cb12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[count(. | //*[text() = 'Priority']) = count(//*[text() = 'Priority'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Priority</value>
   </webElementProperties>
</WebElementEntity>
