<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Labels</name>
   <tag></tag>
   <elementGuidId>1d9d4ef5-ba38-455a-b015-c1bd9c9f9e72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[count(. | //*[text() = 'Labels']) = count(//*[text() = 'Labels'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Labels</value>
   </webElementProperties>
</WebElementEntity>
