<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CreateIssueTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-01-29T15:24:19</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>2299db03-aa00-4d26-bed7-b7a5cc712d59</testSuiteGuid>
   <testCaseLink>
      <guid>02319e67-7c86-44e7-91fa-615c2a59f55c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Advance/Tests/CreateIssueTests/CreateIssueTest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf994f1d-abc6-4f42-9a6a-feca87924548</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23f31838-cc6a-48c8-a3f1-432f5917fdd6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffac0986-7271-479a-862a-a4a1b229c281</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd737670-c400-4c97-866b-18af206fbc80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efa00213-033b-47c9-b599-037b44536d8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5adaa40f-1056-427d-ad6e-31f7c039341d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ded3f46-11cf-471f-8377-1c63d5a3d77d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
